//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarathonSkills.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemComparateSpeed
    {
        public int ItemComparateSpeedId { get; set; }
        public string ItemName { get; set; }
        public string Image { get; set; }
        public Nullable<decimal> ItemMaxSpeed { get; set; }
    }
}
